# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gaguirre <gio_aguirre19@yahoo.com>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/06/09 21:15:32 by gaguirre          #+#    #+#              #
#    Updated: 2017/08/10 23:27:27 by gaguirre         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC = ft_isascii.c ft_strcat.c  ft_strlen.c  ft_tolower.c ft_isalnum.c ft_isdigit.c ft_strcpy.c  ft_strncat.c ft_toupper.c ft_isalpha.c ft_isprint.c ft_strdup.c ft_strncpy.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strstr.c ft_strnstr.c ft_strcmp.c ft_strncmp.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_memalloc.c ft_atoi.c ft_memdel.c ft_strnew.c ft_strclr.c ft_strdel.c ft_striter.c ft_striteri.c ft_strmap.c ft_strmapi.c ft_strequ.c ft_strnequ.c ft_strsub.c ft_putchar.c ft_putstr.c ft_putendl.c ft_putnbr.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_lstnew.c ft_strjoin.c ft_strtrim.c ft_strsplit.c ft_itoa.c ft_countwords.c ft_lstdelone.c ft_lstdel.c ft_lstadd.c ft_lstiter.c ft_lstmap.c ft_swap.c ft_intlen.c ft_lstsize.c ft_lstprint.c

FLAGS = -Wall -Wextra -Werror -I .

BIN = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(BIN)
		@ar rc $@ $^

%.o: %.c
		@gcc -c $(FLAGS) $< -o $@

clean:
		@rm -rf $(BIN)

fclean: clean
		@rm -rf $(NAME)

re: fclean all
